name: update-calendar
run-name: Update calendar

on:
  workflow_dispatch:
  schedule:
    # Run every hour
    - cron: "0 */1 * * *"

jobs:
  fetch-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download calendar from Nextcloud
        run: curl 'https://files.x-hain.de/remote.php/dav/public-calendars/Yi63cicwgDnjaBHR/?export&accept=jcal' > temp.json

      - name: Create data directory if it doesn't exist
        run: mkdir -p data

      - name: Convert CalDav format to useful JSON
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq ".[2][][1] | map({key:.[0], value:.[3]}) | from_entries" ./temp.json | jq -s > data/calendar.json'
          multiline: true

      - name: Commit and push changes to facts file
        run: |
          git config user.email "robot@github.com"
          git config user.name "${{ github.actor }}"
          git add "data/calendar.json"
          git diff --quiet && git diff --staged --quiet || git commit -m "ci: update calander data file"
          git push

